jobs:
  - name: install_ec2_elasticsearch_job
    type: runSh
    steps:
      - IN: aws_ec2_tf_ssh
      - IN: aws_ec2_tf_info
      - TASK:
          name: install_elasticsearch
          script:
            - echo "$ec2_ins_0_ip"
            - printenv
            - export PUBLIC_SSH_KEY=$(shipctl get_integration_resource_field aws_ec2_tf_ssh "publicKey")
            - echo "$PUBLIC_SSH_KEY"
            - echo $AWS_EC2_TF_SSH_KEYPATH
            - ls -la $AWS_EC2_TF_SSH_KEYPATH
            - chmod 400 $AWS_EC2_TF_SSH_KEYPATH
            - ssh -i $AWS_EC2_TF_SSH_KEYPATH ubuntu@$ec2_ins_0_ip "echo hello world"
