resources:
# Automation scripts repo
  - name: install_ec2_elasticsearch_repo
    type: gitRepo
    integration: "drship_github"
    versionTemplate:
      sourceName: "sample-organisation/install_ec2_elasticsearch" # TODO: rename to devops-recipes
      branch: master


jobs:
  - name: install_ec2_elasticsearch_job
    type: runSh
    steps:
      - IN: install_ec2_elasticsearch_repo
      - IN: aws_ec2_tf_ssh
      - IN: aws_ec2_tf_info
        switch: off
      - TASK:
          name: install_elasticsearch
          runtime:
            container: false
          script:
            - pushd $(shipctl get_resource_state "install_ec2_elasticsearch_repo")
            - scp -i $AWS_EC2_TF_SSH_KEYPATH ./install_elasticsearch.sh ubuntu@$ec2_ins_0_ip:install_elasticsearch.sh
            - ssh -i $AWS_EC2_TF_SSH_KEYPATH ubuntu@$ec2_ins_0_ip "chmod +x install_elasticsearch.sh"
            - ssh -i $AWS_EC2_TF_SSH_KEYPATH ubuntu@$ec2_ins_0_ip "./install_elasticsearch.sh"
            - popd
      - TASK:
          name: test_elasticsearch
          runtime:
            container: false
          script:
            - ssh -i $AWS_EC2_TF_SSH_KEYPATH ubuntu@$ec2_ins_0_ip "curl -X GET 'http://localhost:9200'"
