jobs:
  - name: install_ec2_elasticsearch_job
    type: runSh
    steps:
      - IN: aws_ec2_tf_ssh
      - IN: aws_ec2_tf_info
      - TASK:
          name: install_elasticsearch
          script:
            - echo "$ec2_ins_0_ip"
            - cd ~/.ssh
            - ls
            # - export PRIVATE_SSH_KEY=$(shipctl get_integration_resource_field aws_ec2_tf_ssh "privateKey")
            # - ssh -i private.key ubuntu@$ec2_ins_0_ip "echo hello world"
